osx_image: xcode8.3
language: objective-c
xcode_workspace: SwiftUtilities.xcworkspace
xcode_scheme: SwiftUtilities
xcode_sdk: iphonesimulator10.1
before_install:
    - pod repo update

script:
    - set -o pipefail && xcodebuild test -sdk iphonesimulator -workspace SwiftUtilities.xcworkspace  -scheme SwiftUtilities  CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3'